language: elixir
matrix:
  include:
    - otp_release: 21.3
      elixir: 1.6
    - otp_release: 21.3
      elixir: 1.7
    - otp_release: 22.0
      elixir: 1.7
    - otp_release: 21.3
      elixir: 1.8
    - otp_release: 22.0
      elixir: 1.8
    - otp_release: 22.0
      elixir: 1.9
install:
  - mix local.hex --force
  - mix local.rebar
  - mix deps.get
script:
  - mix test
